newebodac:
  resourceId: newebodac

token:
  validitySeconds: ${tokenValiditySeconds}

encryption:
  key: ${encryptionKey}
  salt: ${encryptionSalt}
  iv: ${encryptionIv}

server:
  port: ${tomcatServerPort}
  ssl:
    enabled: ${sslEnabled}
    key-alias: ${keyAlias}
    key-store: ${keyStore}
    key-store-password: ${keyStorePassword}
    key-store-type: ${keyStoreType}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
      comment-prefix: '#'
      properties.org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
  security:
    oauth2:
      client:
        authentication-scheme: header
  liquibase:
    change-log: classpath:liquibase/master.xml
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ${databasePassword}
    url: ${databaseUrl}
    username: ${databaseUser}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
  mail:
    host: ${mailHost}
    username: ${mailUsername}
    password: ${mailPassword}
    properties:
      mail:
        smtp:
          starttls.enable: true

scheduled-tasks:
  demo-task:
    cron-expression: '0 0 9 * * *'
