newebodac:
  resourceId: newebodac

token:
  validitySeconds: ${tokenValiditySeconds}

refreshToken:
  validitySeconds: ${refreshTokenValiditySeconds}

encryption:
  key: ${encryptionKey}
  salt: ${encryptionSalt}
  iv: ${encryptionIv}

server:
  port: ${tomcatServerPort}
  ssl:
    enabled: ${sslEnabled}
    key-alias: ${keyAlias}
    key-store: ${keyStore}
    key-store-password: ${keyStorePassword}
    key-store-type: ${keyStoreType}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spring:
  quartz:
    job-store-type: jdbc
    properties.org.quartz.threadPool.threadCount: 1
    properties.org.quartz.jobStore.dataSource: quartzDataSource
    properties.org.quartz.dataSource.quartzDataSource.URL: ${databaseUrl}
    properties.org.quartz.dataSource.quartzDataSource.user: ${databaseUser}
    properties.org.quartz.dataSource.quartzDataSource.password: ${databasePassword}
    properties.org.quartz.jobStore.useProperties: true
    properties.org.quartz.dataSource.quartzDataSource.driver: com.mysql.cj.jdbc.Driver
    properties.org.quartz.jobStore.tablePrefix: QRTZ_
    properties.org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
    # Enable HikariCP DB conn Pool
    properties.org.quartz.dataSource.quartzDataSource.provider: hikaricp
  security:
    oauth2:
      client:
        authentication-scheme: header
  liquibase:
    change-log: classpath:liquibase/master.xml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${databasePassword}
    url: ${databaseUrl}
    username: ${databaseUser}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: ${showSqlInLog}
  mail:
    host: ${mailHost}
    username: ${mailUsername}
    password: ${mailPassword}
    properties:
      mail:
        smtp:
          starttls.enable: true

scheduled-tasks:
  send-messages:
    interval: 86400 #one day
  generate-reports:
    interval: 86400 #one day
