package org.motechproject.newebodac.domain.enums;

public enum CallDetailFields {
  PROVIDER_CALL_ID,
  CALL_DETAIL_ID,
  PHONE,
  CALL_STATUS,
  START_TIMESTAMP,
  END_TIMESTAMP,
  NUMBER_OF_ATTEMPTS,
  CALL_DURATION,
  MESSAGE_PERCENT_LISTENED,
  MESSAGE_TIME_LISTENED
}
